### PR TITLE
Support RouteData variables in request object

### PR DESCRIPTION
**Pull request by mdissel**
See ticket #6

### CODE REVIEW

**Comment by Kahbazi** [comment]
Looks good.
Could you please make this an opt-in feature, and add some unit tests?

**Comment by mdissel** [comment]
> Could you please make this an opt-in feature, 

I don't think this is necessary, because the developer is explicitly defining the variables in the Url. If you don't do that, no mapping will happen. Maybe only an opt-in for the possible override if there is a body / json handling.

> and add some unit tests?

currently bit lack of time, but is indeed necessary.

**Comment by Kahbazi** [comment]
Thanks @mdissel. I will merge this PR and add the tests myself.

**Comment by mdissel** [comment]
Thanks! (didn't had the time yet to add the tests)

**Pull request merged**
